version: '2.0'
services:
    elasticsearch-central:
        image: registry.cn-hangzhou.aliyuncs.com/ys_php/hb-es:last
        container_name: es1
        volumes:
        - /pgman/docker-compose-es/node/es1/data:/usr/share/elasticsearch/data
        - /pgman/docker-compose-es/node/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - ES_CLUSTERNAME=elasticsearch
        command: elasticsearch
        ports:
        - "9200:9200"
        - "9300:9300"
        networks:
        - esnet
    elasticsearch-data:
        image: registry.cn-hangzhou.aliyuncs.com/ys_php/hb-es:last
        container_name: es2
        volumes:
        - /pgman/docker-compose-es/node/es2/data:/usr/share/elasticsearch/data
        - /pgman/docker-compose-es/node/es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - ES_CLUSTERNAME=elasticsearch
        command: elasticsearch
        ports:
        - "9201:9200"
        - "9301:9300"
        networks:
        - esnet
    elasticsearch-head:
        image: registry.cn-hangzhou.aliyuncs.com/ys_php/hb-head-es:last
        container_name: head
        volumes:
        - /pgman/docker-compose-es/head/Gruntfile.js:/usr/src/app/Gruntfile.js
        - /pgman/docker-compose-es/head/_site/app.js:/usr/src/app/_site/app.js
        ports:
        - "9100:9100"
        networks:
        - esnet
networks:
    esnet:
        external:
            name: esnet